### ISSUE TITLE
Is this production ready?

### ISSUE THREAD

**Issue by switz** [hirohitokato/SimpleGaplessPlayer#6]
Edit: I got it running.

```
        let queue = dispatch_queue_create("buildingqueue", DISPATCH_QUEUE_SERIAL)

        let assetUrl = NSURL(fileURLWithPath: self.videoPath)
        let asset: AVAsset = AVAsset.assetWithURL(assetUrl) as AVAsset

        asset.loadValuesAsynchronouslyForKeys(["duration"]) {
            dispatch_async(queue) {
                self._player.appendAsset(asset);
                self._player.play()
            }
        }
```

edit 2: Does it not work in the simulator? Seems to only work on the device. Also, no audio?

**Comment by switz** [comment]
Ok, I got it working on the device only, not the simulator. There is no audio, and very often it just repeats the first video rather than playing through all of them.

I'm going to go ahead and assume this isn't ready for production usage, although I wish it was! If you have any info, I'm intrigued to hear it.

Thanks for a cool library!

**Comment by katokichisoft** [comment]
First of all, thank you so much for interesting this library.

As you know, currently I don't build an audio route while playing, because of the development priority. I will implement the audio after I stabilize all features for video (it is near future). And current auto-repeat behavior will be one of the parameter.

By the way, I think it must work on the simulator if there is some movies in the camera roll. I don't know why it doesn't work in your simulator. Do you have some movies in the camera roll? Otherwise, does "Finished gathering video assets."  console log appear when you run the sample app on the simulator?

**Comment by katokichisoft** [comment]
I added autoRepeat property(default = false) to Player class.

**Comment by switz** [comment]
I implemented this into my own project, so I'm using my own video files as sources, not the camera roll. I'll check if SimpleGaplessPlayer works on my simulator once I add videos to my camera roll.

I'm planning on launching a new app (swift) in the next two weeks that could really use this project. However, my app is too close to release to consider using at this point since it's not 100% production ready. But I'd like to stay in the loop and help this project as much as I can. Let me know if I can assist in any way.
